#!/bin/bash

if [ $# == 1 ]
then
git config --global user.email seriousmail07@gmail.com
git add .
#git commit -m "20171018_19_00"
#git commit -m "20171018_19_00"
git commit -m $1
git push origin master
fi

