#!/usr/bin/python
# -*- coding: utf-8 -*-

a = 65; print type(a)
print "Mainīga a vērtība kā dec skaitlis ir:%d"%(a)
print "Mainīga a vērtība kā hex skaitlis ir:%x"%(a)
print "Mainīga a vērtība kā oct skaitlis ir:%o"%(a)
print "Mainīga a vērtība kā simbols skaitlis ir:%c"%(a)
a = 'A'; print type(a)
print "Mainīga a vērtība kā dec skaitlis ir:%d"%(ord(a))
print "Mainīga a vērtība kā hex skaitlis ir:%x"%(ord(a))
print "Mainīga a vērtība kā oct skaitlis ir:%o"%(ord(a))
print "Mainīga a vērtība kā simbols skaitlis ir:%c"%(ord(a))
a = '\n'; print type(a)
print "Mainīga a vērtība kā dec skaitlis ir:%d"%(ord(a))
print "Mainīga a vērtība kā hex skaitlis ir:%x"%(ord(a))
print "Mainīga a vērtība kā oct skaitlis ir:%o"%(ord(a))
print "Mainīga a vērtība kā simbols skaitlis ir:%c"%(ord(a))
a = 8.5
print type(a)
print "Mainīga a vērtība kā dec skaitlis ir:%d"%(a)
print "Mainīga a vērtība kā hex skaitlis ir:%x"%(a)
print "Mainīga a vērtība kā oct skaitlis ir:%o"%(a)
# print "Mainīga a vērtība kā simbols skaitlis ir:%c"%(a)
print "Mainīga a vērtība kā reāls skaitlis ir:%10.3f"%(a)
